export const DA_NANG_WARDS: string[] = [
  'Hải Châu',
  'Hòa Cường',
  'Thanh Khê',
  'An Khê',
  'An Hải',
  'Sơn Trà',
  'Ngũ Hành Sơn',
  'Hòa Khánh',
  'Hải Vân',
  'Liên Chiểu',
  'Cẩm Lệ',
  'Hòa Xuân',
];

export const VIETNAM_BANKS = [
    { name: 'Ngân hàng TMCP Ngoại thương Việt Nam', shortName: 'Vietcombank' },
    { name: 'Ngân hàng TMCP Kỹ thương Việt Nam', shortName: 'Techcombank' },
    { name: 'Ngân hàng TMCP Công thương Việt Nam', shortName: 'VietinBank' },
    { name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam', shortName: 'Agribank' },
    { name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam', shortName: 'BIDV' },
    { name: 'Ngân hàng TMCP Quân đội', shortName: 'MB Bank' },
    { name: 'Ngân hàng TMCP Á Châu', shortName: 'ACB' },
    { name: 'Ngân hàng TMCP Sài Gòn Thương Tín', shortName: 'Sacombank' },
    { name: 'Ngân hàng TMCP Việt Nam Thịnh vượng', shortName: 'VPBank' },
    { name: 'Ngân hàng TMCP Tiên Phong', shortName: 'TPBank' },
    { name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh', shortName: 'HDBank' },
    { name: 'Ngân hàng TMCP Sài Gòn - Hà Nội', shortName: 'SHB' },
    { name: 'Ngân hàng TMCP Quốc tế Việt Nam', shortName: 'VIB' },
    { name: 'Ngân hàng TMCP Hàng hải Việt Nam', shortName: 'MSB' },
    { name: 'Ngân hàng TMCP Đông Nam Á', shortName: 'SeABank' },
    { name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam', shortName: 'Eximbank' },
    { name: 'Ngân hàng TNHH MTV Shinhan Việt Nam', shortName: 'Shinhan Bank' },
    { name: 'Ngân hàng TNHH MTV Standard Chartered Việt Nam', shortName: 'Standard Chartered' },
    { name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)', shortName: 'HSBC' },
    { name: 'Ngân hàng TMCP Sài Gòn', shortName: 'SCB' },
];